# in .bashrc / .zshrc
export SSH_AUTH_SOCK=/home/sacha/.gnupg/S.gpg-agent.ssh
export CHROMIUM_FLAGS="--force-device-scale-factor=1.75"

# hack - how to move this line in a systemd unit?
/bin/echo UPDATESTARTUPTTY | gpg-connect-agent > /dev/null
