set -s escape-time 0
set-option -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
source-file ~/.config/tmux/rose-pine-theme.conf

set -g prefix M-q
bind M-t send-prefix

set -g mouse on
bind -n WheelUpPane if -F '#{alternate_on}' 'send-keys Up' 'if -F "#{mouse_any_flag}" "send -M" "copy-mode -e; send-keys -M"'
bind -n WheelDownPane if -F '#{alternate_on}' 'send-keys Down' 'send-keys -M'

set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}#{?#{==:#{pane_current_command},fish},, › #{pane_current_command}}'

bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

set-hook -g after-split-window 'select-layout -E'
set-hook -g pane-exited 'select-layout -E'

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-t new-window -a -c "#{pane_current_path}"
bind -n M-r next-window
bind -n M-n previous-window

bind -n M-Space copy-mode

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
set -g focus-events on

set -g status-position top
set -g status-justify left
set -g status-left-length 50
set -g status-right-length 100
set -g status-left ''
set -g window-status-separator ''
set -g display-panes-time 2000
set -g clock-mode-style 24

set -q mode-key vi
bind-key -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X scroll-down
