---
- name: install desktop packages
  pacman: name={{ item }} state=latest
  with_items:
    - xorg-server
    - "{{ libgl }}"
    - xf86-input-libinput
    - xf86-video-intel
    - xorg-xbacklight
    - emacs
    - i3-wm
    - i3lock
    - i3status
    - dmenu
    - conky
    - sddm
    - st
    - xfce4-terminal
    - pulseaudio
    - pavucontrol
    - compton
    - ttf-dejavu
    - adobe-source-code-pro-fonts
    - gajim
    - feh
    - firefox
    - thunderbird
    - sxiv
    - phonon-qt4-gstreamer
    - kdegraphics-okular
    - transmission-qt
    - qt4
    - vlc
  tags: pkgs

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  tags: pkgs

- name: install aur desktop packages
  include: pkg.yml
  vars:
    pkg_name: "{{ item }}"
  with_items:
    - nextcloud-client
  tags: pkgs

- name: Disable 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: set x11 layout
  template:
    src: xorg/keyboard-layout.conf.j2
    dest: /etc/X11/xorg.conf.d/10-keyboard-layout.conf

- name: sddm configuration
  template:
    src: sddm/xsetup.j2
    dest: /usr/share/sddm/scripts/Xsetup
    mode: 0755

- name: enable sddm
  service:
    name: sddm
    enabled: true
