---
- name: set x11 layout
  template:
    src: xorg/keyboard-layout.conf.j2
    dest: /etc/X11/xorg.conf.d/10-keyboard-layout.conf

- name: sddm configuration
  template:
    src: sddm/xsetup.j2
    dest: /usr/share/sddm/scripts/Xsetup
    mode: 0755

- name: enable sddm
  service:
    name: sddm
    enabled: true
