[palette.light]
black0 = "#F8F9FA"
black1 = "#F8F9FA"
black2 = "#EBEEF0"
black3 = "#EBEEF0"
black4 = "#828E9F"
black5 = "#828E9F"
white = "#5C6166"
red = "#F07171"
green = "#86B300"
yellow = "#F2AE49"
orange = "#FFAA33"
blue = "#399EE6"
blue2 = "#3199e1"
purple = "#A37ACC"
magenta = "#A37ACC"
cyan = "#4CBF99"
cyan2 = "#46ba94"
green2 = "#6cbf43"

[palette.dark]
black0 = "#0A0E14"
black1 = "#1F2430"
black2 = "#242936"
black3 = "#2D3340"
black4 = "#4D5566"
black5 = "#8A9199"
white = "#CCCAC2"
red = "#f28779"
green = "#D5FF80"
green2 = "#87d96c"
yellow = "#FFD173"
orange = "#FFCC66"
blue = "#73d0ff"
blue2 = "#6dcbfa"
purple = "#DFBFFF"
magenta = "#DFBFFF"
cyan = "#95e6cb"
cyan2 = "#90e1c6"

[themes.bat]
light = "ayu-light"
dark = "ayu-mirage"

[themes.ghostty]
light = "Ayu Light"
dark = "Ayu Mirage"

[themes.k9s]
default = "ayu"

[themes.lfk]
light = "ayu-light"
dark = "ayu-mirage"

[themes.nvim]
plugin = "https://github.com/shatur/neovim-ayu"
colorscheme = "ayu"

[themes.yazi]
light = "ayu-light"
dark = "ayu-mirage"
packages = []

[themes.zellij]
default = "ayu-mirage"
light = "ayu-light"
dark = "ayu-mirage"

[system_themes.gtk]
light = "Adwaita"
dark = "Adwaita-dark"

[system_themes.icons]
default = "Papirus"

[system_themes.kde]
light = "org.kde.breeze.desktop"
dark = "org.kde.breezedark.desktop"
