[palette.light]
black0 = "#FFFCF0"
black1 = "#F2F0E5"
black2 = "#E6E4D9"
black3 = "#CECDC3"
black4 = "#9F9D96"
black5 = "#6F6E69"
white = "#100F0F"
red = "#AF3029"
green = "#66800B"
yellow = "#AD8301"
orange = "#BC5215"
blue = "#205EA6"
purple = "#5E409D"
magenta = "#A02F6F"
cyan = "#24837B"

[palette.dark]
black0 = "#100F0F"
black1 = "#1C1B1A"
black2 = "#282726"
black3 = "#403E3C"
black4 = "#575653"
black5 = "#878580"
white = "#CECDC3"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
orange = "#DA702C"
blue = "#4385BE"
purple = "#8B7EC8"
magenta = "#CE5D97"
cyan = "#3AA99F"

[themes.bat]
light = "flexoki-light"
dark = "flexoki-dark"

[themes.ghostty]
light = "Flexoki Light"
dark = "Flexoki Dark"

[themes.k9s]
default = "flexoki"

[themes.lfk]
light = "flexoki-light"
dark = "flexoki-dark"

[themes.nvim]
plugin = "https://github.com/kepano/flexoki-neovim"
colorscheme = "flexoki"

[themes.yazi]
light = "flexoki-light"
dark = "flexoki-dark"
packages = []

[themes.zellij]
default = "flexoki-dark"
light = "flexoki-light"
dark = "flexoki-dark"

[system_themes.gtk]
light = "Adwaita"
dark = "Adwaita-dark"

[system_themes.icons]
default = "Papirus"

[system_themes.kde]
light = "org.kde.breeze.desktop"
dark = "org.kde.breezedark.desktop"
