- name: install network-manager
  pacman: name={{ item }} state=latest update_cache=yes
  with_items:
    - networkmanager
    - network-manager-applet
  when: network.network_manager == True

- name: create networkd directory
  file:
    path: /etc/systemd/network
    state: directory
  when: network.networkd == True

- name: create {{ network.interface }} interface conf
  template:
    src: network.j2
    dest: /etc/systemd/network/{{ network.interface }}.network
  notify: restart systemd-networkd
  when: network.networkd == True

- name: dns resolvers
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: network.networkd == True

- name: start networkd
  service:
    name: systemd-networkd
    state: started
    enabled: yes
  when: network.networkd == True

- name: start network-manager
  service:
    name: NetworkManager
    state: started
    enabled: yes
  when: network.network_manager == True
- meta: flush_handlers