- name: install archlinux packages
  pacman: name={{ item }} state=latest update_cache=yes
  with_items:
    - base
    - base-devel
    - emacs-nox
    - vim
    - tmux
    - gdisk
    - btrfs-progs
    - grub
    - efibootmgr
    - w3m
    - ansible
    - git
    - openssh
    - wpa_supplicant
    - bash-completion
  tags: pkgs

- name: remove vi
  pacman: name=vi state=absent

- name: link vim to vi
  file:
    src: /usr/bin/vim
    dest: /usr/bin/vi
    state: link
    force: yes
