- name: update cache
  pacman: update_cache=yes

- name: update system
  pacman: upgrade=yes

- name: install system packages
  pacman: name={{ item }} state=latest
  with_items:
    - base
    - base-devel
    - vim
    - tmux
    - gdisk
    - btrfs-progs
    - grub
    - efibootmgr
    - w3m
    - ansible
    - git
    - openssh
    - wpa_supplicant
    - bash-completion
  tags: pkgs
