#!/usr/bin/env bash
# Source: https://github.com/carnager/rofi-pass/blob/master/rofi-pass
#
_clip_in() {
   pbcopy
}
selected_password=$(gopass list -f | choose)
if [ -z $selected_password ]; then
    exit
fi
pass_tmp=$(gopass show -n -u $selected_password)
declare -a keys
keys+=("pass")
pass_otp_value=$(printf '%s' "${pass_tmp}" | grep 'otpauth://')
if [ ! -z $pass_otp_value ]; then
    keys+=("otp")
fi

pass_key_value=$(printf '%s' "${pass_tmp}" | grep ': ')
while read -r LINE; do
    _id="${LINE%%: *}"
    keys+=($_id)
done < <(printf '%s\n' "${pass_key_value}")

action=$(
    for k in ${keys[@]}; do
        echo $k
    done | choose)

if [ -z $action ]; then
    exit
fi
case $action in
    pass)
        pass=$(gopass show -o $selected_password)
        ;;
    otp)
        pass=$(gopass otp -o $selected_password)
        ;;
    *)
        pass=$(gopass show -o $selected_password $action)
        ;;
esac

printf '%s' "$pass" | _clip_in
